import { settingsthemecomponent } from "./langObject";
const {
  _impulse,
  _impulseplus,
  _impulseplusplus,
  _neuralcore,
  _fireworks,
  _interstellar,
  _painter,
  _photons,
  _rainbow,
  _space,
  // _light,
  _rain,
  _inferno,
  _snakes,
  _matrix,
  _fountain,
  _snow,
  _network,
  _wave,
  _dark,
  // _daysnow,
  _drawworm,
  _galaxy,
  // _imagination,
  // _particlehelix,
  _particles,
  _parts,
  _smoke,
  _spacespider,
  _spaceworm,
  _stars,
  _tunnel,
} = settingsthemecomponent;
// onClick separate
const basicthemes = [
  {
    divClassName: "form-check form-check-inline ml-4",
    inputClassName: "form-check-input",
    value: "impulse",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "impulse",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "impulse",
    isPremiumTheme: false,
    text: _impulse,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "impulseplus",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "impulseplus",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "impulseplus",
    isPremiumTheme: false,
    text: _impulseplus,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "impulseplusplus",
    checked:
      JSON.parse(localStorage.getItem("isDarkTheme")) === "impulseplusplus",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "impulseplusplus",
    isPremiumTheme: false,
    text: _impulseplusplus,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "dark",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "dark",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "dark",
    isPremiumTheme: false,
    text: _dark,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "neuralcore",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "neuralcore",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "neuralcore",
    isPremiumTheme: false,
    text: _neuralcore,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "fireworks",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "fireworks",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "fireworks",
    isPremiumTheme: false,
    text: _fireworks,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "interstellar",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "interstellar",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "interstellar",
    isPremiumTheme: false,
    text: _interstellar,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "painter",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "painter",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "painter",
    isPremiumTheme: false,
    text: _painter,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "photons",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "photons",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "photons",
    isPremiumTheme: false,
    text: _photons,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "rainbow",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "rainbow",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "rainbow",
    isPremiumTheme: false,
    text: _rainbow,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "space",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "space",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "space",
    isPremiumTheme: false,
    text: _space,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "rain",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "rain",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "rain",
    isPremiumTheme: false,
    text: _rain,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "inferno",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "inferno",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "inferno",
    isPremiumTheme: false,
    text: _inferno,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "snakes",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "snakes",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "snakes",
    isPremiumTheme: false,
    text: _snakes,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "matrix",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "matrix",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "matrix",
    isPremiumTheme: false,
    text: _matrix,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "fountain",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "fountain",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "fountain",
    isPremiumTheme: false,
    text: _fountain,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "snow",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "snow",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "snow",
    isPremiumTheme: false,
    text: _snow,
  },
  {
    divClassName: "form-check form-check-inline",
    inputClassName: "form-check-input",
    value: "network",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "network",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "network",
    isPremiumTheme: false,
    text: _network,
  },
  {
    divClassName: "form-check form-check-inline pr-4",
    inputClassName: "form-check-input",
    value: "waves",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "waves",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "waves",
    isPremiumTheme: false,
    text: _wave,
  },
];

const premiumthemes = [
  // {
  //   divClassName: "form-check form-check-inline ml-4 bg-warning",
  //   inputClassName: "form-check-input",
  //   value: "daysnow",
  //   checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "daysnow",
  //   labelClassName: "form-check-label",
  //   labelStyle: {
  //     whiteSpace: "nowrap",
  //   },
  //   htmlFor: "daysnow",
  // (isPremiumTheme: true),
  //   text: _daysnow,
  // },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "drawworm",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "drawworm",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "drawworm",
    isPremiumTheme: true,
    text: _drawworm,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "galaxy",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "galaxy",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "galaxy",
    isPremiumTheme: true,
    text: _galaxy,
  },
  // {
  //   divClassName: "form-check form-check-inline ml-4 bg-warning",
  //   inputClassName: "form-check-input",
  //   value: "imagination",
  //   checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "imagination",
  //   labelClassName: "form-check-label",
  //   labelStyle: {
  //     whiteSpace: "nowrap",
  //   },
  //   htmlFor: "imagination",
  // (isPremiumTheme: true),
  //   text: _imagination,
  // },
  // {
  //   divClassName: "form-check form-check-inline ml-4 bg-warning",
  //   inputClassName: "form-check-input",
  //   value: "particlehelix",
  //   checked:
  //     JSON.parse(localStorage.getItem("isDarkTheme")) === "particlehelix",
  //   labelClassName: "form-check-label",
  //   labelStyle: {
  //     whiteSpace: "nowrap",
  //   },
  //   htmlFor: "particlehelix",
  // (isPremiumTheme: true),
  //   text: _particlehelix,
  // },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "particles",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "particles",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "particles",
    isPremiumTheme: true,
    text: _particles,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "parts",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "parts",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "parts",
    isPremiumTheme: true,
    text: _parts,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "smoke",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "smoke",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "smoke",
    isPremiumTheme: true,
    text: _smoke,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "spacespider",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "spacespider",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "spacespider",
    isPremiumTheme: true,
    text: _spacespider,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "spaceworm",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "spaceworm",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "spaceworm",
    isPremiumTheme: true,
    text: _spaceworm,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "stars",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "stars",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "stars",
    isPremiumTheme: true,
    text: _stars,
  },
  {
    divClassName: "form-check form-check-inline ml-4 bg-warning",
    inputClassName: "form-check-input",
    value: "tunnel",
    checked: JSON.parse(localStorage.getItem("isDarkTheme")) === "tunnel",
    labelClassName: "form-check-label",
    labelStyle: {
      whiteSpace: "nowrap",
    },
    htmlFor: "tunnel",
    isPremiumTheme: true,
    text: _tunnel,
  },
];

export default function (isPremium) {
  if (isPremium) {
    return [...basicthemes, ...premiumthemes];
  }
  return basicthemes;
}
