// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE;";
export const ADD_PROFILE_IMAGE = "ADD_PROFILE_IMAGE";
// Profile
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
// Forum
export const CREATE_FORUM_POST = "CREATE_FORUM_POST";
export const GET_ALL_FORUM_POSTS = "GET_ALL_FORUM_POSTS";
export const GET_FORUM_POST_BY_ID = "GET_FORUM_POST_BY_ID";
export const DELETE_FORUM_POST_SUCCESS = "DELETE_FORUM_POST_SUCCESS";
export const DELETE_FORUM_POST_FAILURE = "DELETE_FORUM_POST_FAILURE";
export const EDIT_FORUM_POST = "EDIT_FORUM_POST";
export const SAVE_FORUM_POST = "SAVE_FORUM_POST";
export const FORUM_POST_ADD_COMMENT = "FORUM_POST_ADD_COMMENT";
export const FORUM_POST_EDIT_COMMENT = "FORUM_POST_EDIT_COMMENT";
export const FORUM_POST_GET_COMMENTS = "FORUM_POST_GET_COMMENTS";
export const FORUM_POST_DELETE_COMMENT = "FORUM_POST_DELETE_COMMENT";
export const FORUM_POST_ADD_REPLY = "FORUM_POST_ADD_REPLY";
export const FORUM_POST_GET_REPLIES = "FORUM_POST_GET_REPLIES";
export const FORUM_POST_GET_REPLY = "FORUM_POST_GET_REPLY";
export const FORUM_POST_EDIT_REPLY = "FORUM_POST_EDIT_REPLY";
export const FORUM_POST_DELETE_REPLY = "FORUM_POST_DELETE_REPLY";
export const FORUM_POST_DISMISS = "FORUM_POST_DISMISS";
export const FORUM_ERROR = "FORUM_ERROR";
// Images
export const CREATE_IMAGE = "CREATE_IMAGE";
export const LIKE_IMAGE = "LIKE_IMAGE";
export const DISLIKE_IMAGE = "DISLIKE_IMAGE";
export const IMPULSIFY_IMAGE = "IMPULSIFY_IMAGE";
export const GET_IMAGES = "GET_IMAGES";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const IMAGE_ERROR = "IMAGE_ERROR";
export const ADD_COMMENT = "ADD_COMMENT";
export const WIPE_IMAGES = "WIPE_IMAGES";
// Videos
export const CREATE_VIDEO = "CREATE_VIDEO";
export const GET_VIDEOS = "GET_VIDEOS";
export const GET_VIDEO = "GET_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const VIDEO_COMMENT = "VIDEO_COMMENT";
export const VIDEO_EDIT_COMMENT = "VIDEO_EDIT_COMMENT";
export const VIDEO_DELETE_COMMENT = "VIDEO_DELETE_COMMENT";
export const VIDEO_GET_COMMENTS = "VIDEO_GET_COMMENTS";
export const VIDEO_ADD_REPLY = "VIDEO_ADD_REPLY";
export const VIDEO_GET_REPLIES = "VIDEO_GET_REPLIES";
export const VIDEO_GET_REPLY = "VIDEO_GET_REPLY";
export const VIDEO_EDIT_REPLY = "VIDEO_EDIT_REPLY";
export const VIDEO_DELETE_REPLY = "VIDEO_DELETE_REPLY";
export const VIDEO_SEARCH = "VIDEO_SEARCH";
export const VIDEO_ERROR = "VIDEO_ERROR";
// All media
export const GET_ALL_MY_MEDIA = "GET_ALL_MY_MEDIA";
export const SET_BULK_MEDIA = "SET_BULK_MEDIA";
export const WIPE_ALL_MEDIA = "WIPE_ALL_MEDIA";
export const ALL_MEDIA_ERROR = "ALL_MEDIA_ERROR";
// Notifications
export const GET_NOTIFS = "GET_NOTIFS";
export const GET_NOTIF = "GET_NOTIF";
export const NOTIF_ERROR = "NOTIF_ERROR";
export const POST_NOTIF = "POST_NOTIF";
// Groups
export const GET_GROUPS = "GET_GROUPS";
export const ME_IN_GROUPS = "ME_IN_GROUPS";
export const GET_GROUP = "GET_GROUP";
export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_POST = "CREATE_GROUP_POST";
export const DELETE_GROUP_POST = "DELETE_GROUP_POST";
export const DELETE_GROUP = "DELETE_GROUP";
export const GROUP_ERROR = "GROUP_ERROR";
// Status
export const CREATE_STATUS = "CREATE_STATUS";
export const GET_ALL_STATUSES = "GET_ALL_STATUSES";
export const GET_MY_STATUSES = "GET_MY_STATUSES";
export const GET_PERSONS_STATUSES = "GET_PERSONS_STATUSES";
export const DELETE_STATUS = "DELETE_STATUS";
export const EDIT_STATUS = "EDIT_STATUS";
export const ADD_COMMENT_TO_STATUS = "ADD_COMMENT_TO_STATUS";
export const GET_COMMENTS_OF_STATUS = "GET_COMMENTS_OF_STATUS";
export const EDIT_COMMENT_OF_STATUS = "EDIT_COMMENT_OF_STATUS";
export const DELETE_COMMENT_OF_STATUS = "DELETE_COMMENT_OF_STATUS";
export const REPLY_TO_COMMENT_OF_STATUS = "REPLY_TO_COMMENT_OF_STATUS";
export const EDIT_REPLY_TO_COMMENT_OF_STATUS =
  "EDIT_REPLY_TO_COMMENT_OF_STATUS";
export const GET_ALL_REPLIES_TO_COMMENT_OF_STATUS =
  "GET_ALL_REPLIES_TO_COMMENT_OF_STATUS";
export const DELETE_REPLY_TO_COMMENT_OF_STATUS =
  "DELETE_REPLY_TO_COMMENT_OF_STATUS";
export const STATUS_ERROR = "STATUS_ERROR";
